##################
### DEPLOYMENT ###
##################
# Required values
name: rhbk
# Number of instances.
instances: 1
# Name of namespace
namespace: rhbk-dev
nodeSelector: app=rhbk
##custom image
image: quay.io/rh-ee-bcordeir/rhbk:dev-91463cd49f2592e6d159aed19848fe1c01f4d33c
##################
###### HTTP ######
##################
http:
  tlsSecret: tls-secret
# use service serving certificate
tlsSecret:
  servingCert: true
##################
#### HOSTNAME ####
##################
hostname:
  strict: false
  hostname: rhbk-dev.apps.cluster-hd67g.hd67g.sandbox1664.opentlc.com
ingress:
  enabled: false
##################
### TRUSTSTORE ###
##################
#truststores:
#    secret:
#      name: <change>
##################
#### RESOURCES ####
##################
resources:
  requests:
    cpu: 1000m
    memory: 1250Mi
  limits:
    cpu: 3000m
    memory: 1500Mi
