{{- if .Values.deployOperator }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.name }}-subscription
  namespace: {{ .Values.namespace | default .Values.name | quote }}
  labels:
    {{- include "rhbk.labels" . | nindent 4 }}
    {{- include "rhbk.operatorLabel" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: {{ .Values.operator.channel }}
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
  startingCSV: {{ .Values.operator.startingCSV }}
{{- end}}